## Living Room
# Now in configuration.yaml
#- platform: amcrest
#  name: Living Room
#  host: 192.168.10.51
#  username: admin
#  password:                        !secret AMCREST_PASSWORD

#- platform: mjpeg
#  mjpeg_url: http://192.168.10.51/cgi-bin/snapshot.cgi?channel=0
#  mjpeg_url: http://admin:012749@192.168.10.51/axis-cgi/mjpg/video.cgi?camera=1&resolution=320X240
#  port: 80
#  stream_source: mjpeg
##  stream_source: rtsp

# Crashes HA
#- platform: ffmpeg
#  name: "Living Room"
#  #Works on VLC player
#  input: rtsp://admin:012749@192.168.10.51:80/cam/realmonitor?channel=1&subtype=1

# Poor resolution
#- platform: mjpeg
#  mjpeg_url: http://admin:012749@192.168.10.51/cgi-bin/mjpg/video.cgi?channel=1&subtype=1
#  name: "living Room"

# Front Door
- platform: ring
#  name: Front Door
  scan_interval: 90

# Front Garage
#- platform: amcrest
#  mjpeg_url: http://admin:012749@192.168.10.228/snapshot.cgi
#  mjpeg_url: http://admin:012749@192.168.10.56/snapshot.cgi
#  name: Front Garage

# Front Outside
#- platform: mjpeg
#  mjpeg_url: http://admin:012749@192.168.10.52/snapshot.cgi
#  name: Front Camera


#- platform: foscam
#  ip: 192.168.10.55
#  username: admin
#  password: 012749
#  name: Garage

#  still_image_url: http://192.168.10.55/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=012749
  
#  still_image_url: http://192.168.10.16/garage.php

#- platform: mjpeg
#  mjpeg_url: http://admin:012749@192.168.10.55/snapshot.cgi
#  name: Garage
#  mjpeg_url: http://192.168.10.55/videostream.cgi?user=admin&pwd=012749
#  mjpeg_url: http://admin:mtncad@192.168.10.55/snapshot.cgi?resolution=320X240

# Family Room
- platform: mjpeg
  mjpeg_url: http://admin:012749@192.168.10.54/snapshot.cgi
#  ip: 192.168.10.54
#  username: admin
#  password: 012749
  name: Family Room

- platform: generic
  still_image_url: http://admin:012749@192.168.10.56/snapshot.cgi
  name: Outside Back

#- platform: mjpeg
#  mjpeg_url: http://admin:mtncad@foscam.mtncad.com/snapshot.cgi?resolution=320X240
##  ip: foscam.mtncad.com
##  username: admin
##  password: mtncad
#  name: 'Office'

#- platform: generic
#  still_image_url: http://mcoyne50.ddns.net:800/snapshot.jpg
#  name: Mike's Gate
