homeassistant:
  name:                              Home
  latitude:                          !secret LATITUDE
  longitude:                         !secret LONGITUDE
  elevation:                         1057
  unit_system:                       imperial
  time_zone:                         America/New_York
      
# Enables the frontend
frontend:
  javascript_version:                latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles.html  
  
  
logger:
  default:                           warning
# Show links to resources in log and frontend
#introduction:

# Enables configuration UI
config:

# Enables support for tracking state changes over time.
recorder:
  db_url:                            !secret DB_URL
  # Delete events and states older than 7 days every day
  purge_interval:                    1
  purge_keep_days:                   7

http:
  base_url:                          !secret BASE_URL
  api_password:                      !secret API_PASSWORD

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

