alias: Disable Patio PIR on startup if daylight
initial_state: true
trigger:
  platform: event
  event_type: homeassistant_start
condition:
  condition: state
  entity_id: sun.sun
  state: 'above_horizon'
action:
  - service: switch.turn_off
    entity_id: switch.patio_light_auto
    
    
  