alias:  Kiosk Mode On
initial_state: true
trigger:
  platform: state
  entity_id: input_boolean.kiosk_mode
  from: 'off'
  to: 'on'
action:
  - service: group.set_visibility
    entity_id: group.kiosk
    data:
      visible: True

