alias: Lock Front and Side Doors Late
trigger:
  platform: time
  # When 'at' is used, you cannot also match on hour, minute, seconds.
  # Military time format.
  at: '22:30:00'
action:
  - service: lock.lock
    data:
      entity_id: lock.schlage_be469_touchscreen_deadbolt_locked
      code: 0127
  - service: lock.lock
    data:
      #entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
      entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked_2
      code: 0127
  - service: notify.jerry
    data:
      title: "Locking Front and Side Door"
      message: "Locking Front and Side Doors, it's 10:30 pm"
#  - service: switch.turn_off
#    entity_id: switch.wemo_mini_2,light.hue_white_lamp_2 # Christmas Tree
 