alias: Monitor Incoming Traffic
initial_state: true
trigger:
  platform: state
  entity_id: sensor.snmp_wan_in
action:
  - service: input_number.set_value
    data_template:
    #service_template:
      entity_id: input_number.internet_traffic_delta_in
      value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'
