alias: Motion detected after dark back driveway
trigger:
  platform: state
  entity_id: binary_sensor.back_driveway_pir_sensor
  from: "off"
  to: "on"
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  - service: media_player.play_media
    entity_id: media_player.speaker
    data:
      media_content_id: /home/homeassistant/.homeassistant/doorbell-2.mp3
      media_content_type: music
  
  - service: tts.google_say
    entity_id: media_player.speaker
    data_template:
      message: 'Back driveway.'

  - service: notify.jerry
    data:
      title: "Back driveway"
      message: 'Motion detected on back driveway.'
