alias: Garage Door 2 Open
initial_state: true
trigger:
  platform: time
  # When 'at' is used, you cannot also match on hour, minute, seconds.
  # Military time format.
  at: '22:30:00'
condition:
  condition: state
  entity_id: binary_sensor.back_garage_door_tilt_sensor
  state: 'on'
action:
  - service: notify.jerry
    data:
      title: Back Garage Door Open
      message: 'Back Garage Door is Open - Verify if this is correct and it needs to be closed'
  - service: tts.google_say
    entity_id: media_player.speaker
    data_template:
      message: "It's 10:30 PM and the back garage door is open."
