alias: 'Outside Lights off at sunrise'
initial_state: true
trigger:
  platform: sun
  event: 'sunrise'
action:
  - service: scene.turn_on
    entity_id: scene.day

#  - service: notify.jerry
#    data:
#      title: "Sunrise"
#      message: "Sunrise"
