alias: 'Security Lights on at sunset'
trigger:
  platform: sun
  event: 'sunset'
action:
  - service: scene.turn_on
    entity_id: scene.night

  - service: notify.jerry
    data:
      title: "Sunset"
      message: "Sunset"
  
